service: serverless

provider:
  name: aws
  runtime: nodejs8.10
#  profile: femasters
  region: us-east-1
  stage: dev

plugins:
  - serverless-offline
  - serverless-finch

custom:
  client:
    bucketName: methset # (see Configuration Parameters below)
    # [other configuration parameters] (see Configuration Parameters below)
    #
functions:
  api:
    handler: server/src/api/index.handler
    events:
      - http:
          method: Any
          path: /{proxy+}
          cors: true
